version: "3.9"

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.databasus.service: databasus
  traefik.http.services.databasus.loadbalancer.server.port: 4005

services:
  databasus:
    image: databasus/databasus:latest
    container_name: databasus
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - /volume5/storage/docker-data/databasus/data/:/databasus-data
    restart: always